wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1633783302
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.8
      5: 0.12.4
      8:
      - 3
      - 5
